### ISSUE TITLE
Got `Uncaught TypeError: node.attributes.href is undefined`

### ISSUE THREAD

**Issue by vtmocanu** [aidistan/freshrss-extensions#1]
I've installed the theme switcher plugin, enabled it, choose the different themes, but it does not do anything upon theme change, i've refreshed, but it does not seem to work, the theme changes on firefox, but not on the site itself.
Is this supposed to work on MacOS?
Thanks,
Vlad

**Comment by aidistan** [comment]
Hi @WladyX , thanks for reporting this issue. I have tested ThemeModeSynchronizer v1.1.2 on MacOS, it should work fine.

I guess it has nothing related to the OS. What's the version of your Firefox? Try upgrade the browser to the latest version at first?

**Comment by aidistan** [comment]
Also, please check the output in the console. For browsers not supporting MediaQuery, you may see the following prompt:

```
Due to the limitation of current browser, ThemeModeSynchronizer extension cannot work as expected.
```

**Comment by vtmocanu** [comment]
i get this in the console on FF 104.0.1:
```
Uncaught TypeError: node.attributes.href is undefined
    getCurrentTheme https://sss/ext.php?f=xExtension-ThemeModeSynchronizer/static/main.js&t=js&1661611620:15
    syncWithSystemMode https://sss/ext.php?f=xExtension-ThemeModeSynchronizer/static/main.js&t=js&1661611620:31
    <anonymous> https://sss/ext.php?f=xExtension-ThemeModeSynchronizer/static/main.js&t=js&1661611620:53
    EventListener.handleEvent* https://sss/ext.php?f=xExtension-ThemeModeSynchronizer/static/main.js&t=js&1661611620:1
ext.php:15:27
```

**Comment by vtmocanu** [comment]
It does work on Chrome, so it's probabably a FF addon or setting that breaks this.
Thank you!

**Comment by aidistan** [comment]
> i get this in the console on FF 104.0.1:
> 
> ```
> Uncaught TypeError: node.attributes.href is undefined
>     getCurrentTheme https://sss/ext.php?f=xExtension-ThemeModeSynchronizer/static/main.js&t=js&1661611620:15
>     syncWithSystemMode https://sss/ext.php?f=xExtension-ThemeModeSynchronizer/static/main.js&t=js&1661611620:31
>     <anonymous> https://sss/ext.php?f=xExtension-ThemeModeSynchronizer/static/main.js&t=js&1661611620:53
>     EventListener.handleEvent* https://sss/ext.php?f=xExtension-ThemeModeSynchronizer/static/main.js&t=js&1661611620:1
> ext.php:15:27
> ```

Thanks for reporting these details. I've added a safe navigation at `ThemeModeSynchronizer/static/main.js:15`. Try v1.1.4 if you would like to use it on your Firefox : )

**Comment by vtmocanu** [comment]
I've pulled master, all good now, thank you for the super fast support!
